### ISSUE TITLE
about gradient view in paper

### ISSUE THREAD

**Issue by boileddd** [zhihou7/BatchFormer#5]
Hello, I'm sorry to bother you.  I don't quite understand the explanation about gradient propagation in this paper. Why does the gradient propagate in other samples with BatchFormer?  Is it reflected in the code?

**Comment by zhihou7** [comment]
With BatchFormer, each example in the mini-batch contributes the optimization of other examples in mini-batch because we build a graph in the batch dimension. Please refer to https://github.com/zhihou7/BatchFormer/blob/f6be150ff9fce2ce4bcc3c0f8953dded9d4f273f/long-tailed_recognition/BalancedSoftmax/run_networks.py#L310 and https://github.com/zhihou7/BatchFormer/blob/f6be150ff9fce2ce4bcc3c0f8953dded9d4f273f/long-tailed_recognition/BalancedSoftmax/run_networks.py#L335

**Comment by boileddd** [comment]
Thank you for your reply. I guess I get it, you are so nice!

**Comment by boileddd** [comment]
Thank you for your reply. I guess I get it, you are so nice!
